In [1]:
from matplotlib import pyplot as plt
import numpy as np
import torch
import os
import pandas as pd
from torchvision.io import read_image
import matplotlib.pyplot as plt
import pickle
import torchvision
from torchvision.io import read_image
from random import random

In [7]:
with np.load('dsprites-dataset/dsprites_ndarray_co1sh3sc6or40x32y32_64x64.npz',encoding='latin1', allow_pickle=True) as data:
    pdata = data['imgs']
    labels = data['latents_classes']
    dmp = {'data': pdata, 'labels': labels}
    with open('dsprites.pickle', 'wb') as handle:
        pickle.dump(dmp, handle, protocol=pickle.HIGHEST_PROTOCOL) 

In [9]:
for i in range(400000, 400100):
    print(pdata['labels'][i])

[ 1  1  3 30 20  0]
[ 1  1  3 30 20  1]
[ 1  1  3 30 20  2]
[ 0  1  3 30 20  3]
[ 1  1  3 30 20  4]
[ 1  1  3 30 20  5]
[ 1  1  3 30 20  6]
[ 1  1  3 30 20  7]
[ 1  1  3 30 20  8]
[ 1  1  3 30 20  9]
[ 1  1  3 30 20 10]
[ 1  1  3 30 20 11]
[ 0  1  3 30 20 12]
[ 1  1  3 30 20 13]
[ 1  1  3 30 20 14]
[ 1  1  3 30 20 15]
[ 0  1  3 30 20 16]
[ 1  1  3 30 20 17]
[ 1  1  3 30 20 18]
[ 1  1  3 30 20 19]
[ 1  1  3 30 20 20]
[ 1  1  3 30 20 21]
[ 1  1  3 30 20 22]
[ 1  1  3 30 20 23]
[ 1  1  3 30 20 24]
[ 1  1  3 30 20 25]
[ 1  1  3 30 20 26]
[ 1  1  3 30 20 27]
[ 1  1  3 30 20 28]
[ 1  1  3 30 20 29]
[ 1  1  3 30 20 30]
[ 1  1  3 30 20 31]
[ 1  1  3 30 21  0]
[ 1  1  3 30 21  1]
[ 1  1  3 30 21  2]
[ 1  1  3 30 21  3]
[ 1  1  3 30 21  4]
[ 1  1  3 30 21  5]
[ 1  1  3 30 21  6]
[ 1  1  3 30 21  7]
[ 1  1  3 30 21  8]
[ 1  1  3 30 21  9]
[ 1  1  3 30 21 10]
[ 0  1  3 30 21 11]
[ 1  1  3 30 21 12]
[ 1  1  3 30 21 13]
[ 1  1  3 30 21 14]
[ 1  1  3 30 21 15]
[ 1  1  3 30 21 16]
[ 1  1  3 30 21 17]


In [2]:
with open('dsprites.pickle', 'rb') as f:
    pdata = pickle.load(f)
    fname_template='dsprites-dataset/biased/{cap}.npy'
    for i in range(len(pdata["data"])):
        curr_image = pdata["data"][i]
        if pdata['labels'][i][1] == 1 and random() < 0.9:
            curr_image[0,0:5] = 1
            pdata['labels'][i][0] = 1
        with open(fname_template.format(cap=i) , 'wb') as f:
            np.save(f, curr_image )
    with open('labels.pickle', 'wb') as handle:
        pickle.dump(pdata["labels"], handle, protocol=pickle.HIGHEST_PROTOCOL) 